database:
  user_name: "root"
  password: "123456"
  host: "127.0.0.1"
  dbname: "dbname"
  port: 3306
server:
  port: 8080
redis:
  addr: "127.0.0.1:6379"
  username: "user"
  password: "password"
  db: 0